from pydantic import BaseModel,Field,EmailStr
from typing import Annotated,Optional
from datetime import datetime

# not used because we also need to upload jd
class createJobSchema(BaseModel):
    title: Annotated[str, Field(title="Job title")]
    description: Annotated[str, Field(title="Job description")]
    experience_level: Annotated[str, Field(title="Experience level")]


# things that are generated by use have to kept optional
class jobResponseSchema(BaseModel):
    model_config = {"from_attributes": True}
    id: Annotated[int, Field(title="Job id")]
    title: Annotated[str, Field(title="Job title")]
    description: Annotated[str, Field(title="Job description")]
    experience_level: Annotated[str, Field(title="Experience level")]
    # automatically generated by FASTAPI
    job_file_path:Annotated[Optional[str],Field(title="Path file for JD")]
    # these two will come from create_job run , hence a part of Optional
    jd_text:Annotated[Optional[str],Field(title="Text in JD",default=None)]
    jd_skills:Annotated[Optional[str],Field(title="Job skills")]
    created_at: Annotated[datetime, Field(title="Job creation time")]
    


class updateJobSchema(BaseModel):
    title: Annotated[Optional[str], Field(title="Job title", default=None)]
    description: Annotated[Optional[str], Field(title="Job description", default=None)]
    experience_level: Annotated[Optional[str], Field(title="Experience level", default=None)]