"""added missing skills

Revision ID: 0ea027db03a7
Revises: 30c63e3b57c2
Create Date: 2026-06-06 23:08:53.514040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea027db03a7'
down_revision: Union[str, Sequence[str], None] = '30c63e3b57c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_table', sa.Column('missing_skills', sa.String(), nullable=True))
    op.alter_column('application_table', 'similarity_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('application_table', 'ats_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_table', 'ats_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('application_table', 'similarity_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('application_table', 'missing_skills')
    # ### end Alembic commands ###
