"""add foreign keys

Revision ID: 30c63e3b57c2
Revises: ed78b067c503
Create Date: 2026-06-01 17:37:01.341024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c63e3b57c2'
down_revision: Union[str, Sequence[str], None] = 'ed78b067c503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'application_table', 'job_table', ['job_id'], ['id'])
    op.create_foreign_key(None, 'application_table', 'resume_table', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'application_table', 'user_table', ['candidate_id'], ['id'])
    op.create_foreign_key(None, 'job_table', 'user_table', ['recruiter_id'], ['id'])
    op.create_foreign_key(None, 'resume_table', 'user_table', ['candidate_id'], ['id'])
    op.drop_column('resume_table', 'ats_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_table', sa.Column('ats_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resume_table', type_='foreignkey')
    op.drop_constraint(None, 'job_table', type_='foreignkey')
    op.drop_constraint(None, 'application_table', type_='foreignkey')
    op.drop_constraint(None, 'application_table', type_='foreignkey')
    op.drop_constraint(None, 'application_table', type_='foreignkey')
    # ### end Alembic commands ###
