"""job jd fields

Revision ID: 4156fb8af5eb
Revises: 12bb2e43687c
Create Date: 2026-05-31 19:51:31.482100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4156fb8af5eb'
down_revision: Union[str, Sequence[str], None] = '12bb2e43687c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_table', sa.Column('job_file_path', sa.String(), nullable=True))
    op.add_column('job_table', sa.Column('jd_text', sa.String(), nullable=True))
    op.add_column('job_table', sa.Column('jd_skills', sa.String(), nullable=True))
    op.drop_column('job_table', 'required_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_table', sa.Column('required_skills', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('job_table', 'jd_skills')
    op.drop_column('job_table', 'jd_text')
    op.drop_column('job_table', 'job_file_path')
    # ### end Alembic commands ###
