"""roadmap

Revision ID: a586822aef29
Revises: 0ea027db03a7
Create Date: 2026-06-06 23:16:51.151793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a586822aef29'
down_revision: Union[str, Sequence[str], None] = '0ea027db03a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_table', sa.Column('learning_roadmap', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_table', 'learning_roadmap')
    # ### end Alembic commands ###
