"""remove similarity score

Revision ID: b08e0c66942e
Revises: d34b648591f5
Create Date: 2026-07-09 19:37:12.116861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08e0c66942e'
down_revision: Union[str, Sequence[str], None] = 'd34b648591f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_tasks_id'), table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    op.drop_column('application_table', 'similarity_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_table', sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['user_table.id'], name=op.f('roadmap_tasks_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_tasks_pkey'))
    )
    op.create_index(op.f('ix_roadmap_tasks_id'), 'roadmap_tasks', ['id'], unique=False)
    # ### end Alembic commands ###
