"""add ats score

Revision ID: ed78b067c503
Revises: 4156fb8af5eb
Create Date: 2026-05-31 20:01:16.512774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed78b067c503'
down_revision: Union[str, Sequence[str], None] = '4156fb8af5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_table', sa.Column('ats_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_table', 'ats_score')
    # ### end Alembic commands ###
